# image: golang:1.10
image: docker:stable

variables:
  DOCKER_DRIVER: overlay2
  # GOPATH: /go

services:
- docker:dind

# cache:
#   paths:
#     - /apt-cache
#     - /go/src/github.com
#     - /go/src/golang.org
#     - /go/src/google.golang.org
#     - /go/src/gopkg.in

before_script:
  - docker info
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  # - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  # - mkdir -p /go/src/github.com/piersharding /go/src/_/builds
  # - cp -r $CI_PROJECT_DIR /go/src/github.com/piersharding/nfsshare-controller
  # - ln -s /go/src/github.com/piersharding /go/src/_/builds/piersharding
  # - cd /go/src/github.com/piersharding/nfsshare-controller && make deps

stages:
  - build

build-containers:
  stage: build
  script:
    - $CI_PROJECT_DIR/build_image.sh
    - cd $CI_PROJECT_DIR && make docker
    - cd $CI_PROJECT_DIR && REPO_PREFIX=registry.gitlab.com/piersharding/nfsshare-controller/ make push

    # - cd /go/src/github.com/piersharding/nfsshare-controller && make docker
    # - docker login registry.gitlab.com
    # - docker build -t registry.gitlab.com/pantomath-io/demo-tools .
    # - push registry.gitlab.com/pantomath-io/demo-tools

