image: docker:stable

variables:
  DOCKER_DRIVER: overlay2
  GOPREFIX: /go/src/github.com/piersharding/
  IMG: nfsshare-controller
  TAG: latest
  GOLANG: golang:1.10

services:
- docker:dind

before_script:
  - docker info
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  - 'echo "ENVIRONMENT: "'
  - env
  - apk add --update make
  - 'echo "CHECKVARS: "'
  - cd ${CI_PROJECT_DIR} && make checkvars

stages:
  - build

build-containers:
  stage: build
  script:
    - cd ${CI_PROJECT_DIR} && make GOLANG=${GOLANG} run_builder
    - docker images
    - ls -latr ${CI_PROJECT_DIR}/bin/
    - cd ${CI_PROJECT_DIR} && make image
    - docker images
    - docker tag ${IMG}:${TAG} ${CI_REGISTRY_IMAGE}/${IMG}:${TAG}
    - docker push ${CI_REGISTRY_IMAGE}/${IMG}:${TAG}
