# image: golang:1.10
image: docker:stable

variables:
  DOCKER_DRIVER: overlay2
  REPO_PREFIX: registry.gitlab.com/piersharding/nfsshare-controller/ 
  IMG: nfsshare-controller
  TAG: latest
  # GOPATH: /go

services:
- docker:dind

# cache:
#   paths:
#     - /apt-cache
#     - /go/src/github.com
#     - /go/src/golang.org
#     - /go/src/google.golang.org
#     - /go/src/gopkg.in

before_script:
  - docker info
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  - 'echo "ENVIRONMENT: "'
  - env

stages:
  - build

build-containers:
  stage: build
  script:
    - cd ${CI_PROJECT_DIR} && ${CI_PROJECT_DIR}/build_image.sh
    - docker images
    - ls -latr ${CI_PROJECT_DIR}/bin/
    - cd ${CI_PROJECT_DIR} && docker build -t ${IMG}:${TAG} .
    - docker images
    - docker tag ${IMG}:${TAG} ${REPO_PREFIX}${IMG}:${TAG}
    - docker push ${REPO_PREFIX}${IMG}:${TAG}
