#image: docker:stable
image: golang:1.10

variables:
  DOCKER_DRIVER: overlay2
  GOPREFIX: /go/src/github.com/piersharding/
  IMG: nfsshare-controller
  TAG: latest
  # GOLANG: golang:1.10

services:
- docker:dind

before_script:
  - docker info
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  - 'echo "ENVIRONMENT: "'
  - env

stages:
  - build

build-containers:
  stage: build
  script:
    # - cd ${CI_PROJECT_DIR} && ${CI_PROJECT_DIR}/build_image.sh
    - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
    - mkdir -p ${GOPREFIX}
    - ln -s ${CI_PROJECT_DIR} ${GOPREFIX}${CI_PROJECT_NAME}
    - cd ${GOPREFIX}${CI_PROJECT_NAME} && make deps
    - cd ${GOPREFIX}${CI_PROJECT_NAME} && make docker
    - docker images
    - ls -latr ${CI_PROJECT_DIR}/bin/
    # - cd ${CI_PROJECT_DIR} && docker build -t ${IMG}:${TAG} .
    # - docker images
    - docker tag ${IMG}:${TAG} ${CI_REGISTRY_IMAGE}/${IMG}:${TAG}
    - docker push ${CI_REGISTRY_IMAGE}/${IMG}:${TAG}
