---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nfsshare-operator
  namespace: kube-system
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: nfsshare-operator
  namespace: kube-system
  labels:
    k8s-app: nfsshare-operator
spec:
  selector:
    matchLabels:
      k8s-app: nfsshare-operator
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: nfsshare-operator
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: ""
      # securityContext:
      #   runAsUser: 1001
      tolerations:
      - key: node.cloudprovider.kubernetes.io/uninitialized
        value: "true"
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      serviceAccountName: nfsshare-operator
      containers:
      - name: nfsshare-operator
        image: ${DOCKER_IMAGE}
        imagePullPolicy: IfNotPresent
        args:
        - --v=5
        - -logtostderr
