apiVersion: v1
kind: Pod
metadata:
  name: nfstest
  namespace: default
  annotations:
    scheduler.alpha.kubernetes.io/affinity: >
      {
        "nodeAffinity": {
          "requiredDuringSchedulingIgnoredDuringExecution": {
            "nodeSelectorTerms": [
              {
                "matchExpressions": [
                  {
                    "key": "kubernetes.io/hostname",
                    "operator": "NotIn",
                    "values": ["k8smaster"]
                  }
                ]
              }
            ]
          }
        }
      }
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: nfstest
    volumeMounts:
        # name must match the volume name below
        - name: nfs
          mountPath: "/mnt"

  restartPolicy: Always
  volumes:
  - name: nfs
    nfs:
      #server: nfs-server.default.svc.cluster.local
      server: 10.103.85.209
      path: "/"
